### PR TITLE
Convert to a gem: 'ministryofjustice-danger'

### PR DESCRIPTION
**Pull request by digitalronin**
This installs danger and any linters required to implement
the Ministry of Justice house style rules for PRs.

### CODE REVIEW

**Comment by digitalronin** [comment]
OK, so the Gemfile is required for Travis to run :( I'll fix it.

**Review by SteveMarshall — CHANGES_REQUESTED** [review]
The code for this looks good 👍

Can you tweak the commit message/PR so the title completes the sentence “If applied, this will…” (at the moment, it's a slightly awkward tense)?

Also, what does someone contributing need to do to push the gem? Can we automate that on merge to master here (or at least document it)?

**Review by SteveMarshall — CHANGES_REQUESTED** [review]
This looks 👍, save one thing: the `Gemfile` could, instead, just use [the `gemspec` directive](http://bundler.io/v1.12/rubygems.html) instead of explicitly listing the gems again. That way, the list of runtime dependencies only has to be maintained in the gemspec.

**Comment by SteveMarshall** [comment]
Also, one of your commits or the PR description should probably mention that this fixes #5…

**Review by SteveMarshall — APPROVED** [review]

**Pull request merged**
